trigger:
- main

jobs:
- job: Test_Linux_Python_3_9
  displayName: 'Test on Linux with Python 3.9'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true
  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -e .
      pytest
    displayName: 'Install dependencies and run tests'

- job: Test_Linux_Python_3_10
  displayName: 'Test on Linux with Python 3.10'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -e .
      pytest
    displayName: 'Install dependencies and run tests'

- job: Test_Linux_Python_3_11
  displayName: 'Test on Linux with Python 3.11'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true
  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -e .
      pytest
    displayName: 'Install dependencies and run tests'

- job: Test_Windows_Python_3_9
  displayName: 'Test on Windows with Python 3.9'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true
  - script: |
      python -m venv venv
      venv\Scripts\activate
      pip install --upgrade pip
      pip install -e .
      pytest
    displayName: 'Install dependencies and run tests'

- job: Test_Windows_Python_3_10
  displayName: 'Test on Windows with Python 3.10'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
  - script: |
      python -m venv venv
      venv\Scripts\activate
      pip install --upgrade pip
      pip install -e .
      pytest
    displayName: 'Install dependencies and run tests'

- job: Test_Windows_Python_3_11
  displayName: 'Test on Windows with Python 3.11'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true
  - script: |
      python -m venv venv
      venv\Scripts\activate
      pip install --upgrade pip
      pip install -e .
      pytest
    displayName: 'Install dependencies and run tests'
