name: Windows
on:
  push:
    branches:
      - main
      - dev-ci
      - dev-py310

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install -e .[test]

      - name: Run tests
        run: |
          venv\Scripts\activate
          pytest
